[package]
name = "pixels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.0"
clap = { version = "4.5.3", features = ["derive"] }
csv = "1.3.0"
serde = "1.0.197"
